### ISSUE TITLE
Move docs to a standard documentation platform

### ISSUE THREAD

**Issue by ryanswart** [nestjs/docs.nestjs.com#116]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request (new chapter/page)
[ ] Support request 
</code></pre>

## Current behaviour
Currently, adding or editing docs requires quite a bit of effort (hand writing HTML, creating Angular components, registering routes) and Angular knowledge. There is also a lack of some functionality present in other project documentation (internationalisation is done via a separate project, no documentation search).

## Expected behaviour
Documentation content is kept separate from implementation code, in an easily readable format (eg. markdown), where adding or editing content is as easy as adding a new documentation file without any extra boilerplate

## What is the motivation / use case for changing the behaviour?
Reducing effort to create and maintain project documentation, as well as increasing accessibility.

## Suggested resolution
By moving to a documentation platform like https://github.com/facebook/docusaurus , we can sacrifice a bit of customisation for reduced implementation effort & easier/faster documentation creation.

**Comment by kamilmysliwiec** [comment]
There is a plan to integrate current docs with markdown very soon.

**Comment by ryanswart** [comment]
I guess it comes down to - "effort to implement markdown parsing for nest docs" vs "effort to customise existing docs platform". Is there anything you have in mind where having a custom doc site is particularly valuable? 

Happy to help transitioning the docs into markdown though, whichever route you end up going. Could even start doing so with Docusaurus and then have the markdown re-rendered in the custom Nest docs platform once its ready.

**Comment by kamilmysliwiec** [comment]
I believe that we should stick with our current docs since they are somewhat dedicated for our platform, designed for the framework's purposes. It's always better to have something specially designed and wrapped up for a higher goal. The missing markdown integration is definitely a huge downside for now, but I'll fix it as soon as possible.

**Comment by andyford** [comment]
Maybe this is a separate topic, but the doc site is difficult to search since there's no first-party/on-site search functionality and since Google domain searches like "site:docs.nestjs.com controller" turn up very little. Even a search like "site:docs.nestjs.com mongoose" turns up nothing (even though "mongoose" is mentioned on the Techniques/Mongo section

**Comment by kamilmysliwiec** [comment]
The documentation has been moved to the markdown syntax now (`content` directory). 

@andyford thanks for reporting, we will work on it
