### ISSUE TITLE
Nestjs Application Lifecycle & Request Lifecycle

### ISSUE THREAD

**Issue by ahrnee** [nestjs/docs.nestjs.com#131]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request (new chapter/page)
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Expected behavior
As a user, I would like to see more detail on the application lifecycle and request lifecycle, so that I can make appropriate implementation choices when I am using the NestJS framework

## What is the motivation / use case for changing the behavior?

- NestJS provides a great toolbox of ways to intercept and interact with a request.  However when these are used together, the order of execution that can be expected is not clear.

 - Additional clarity on the application lifecycle, and the scope and expected lifespan of specific types of objects within it would be helpful for understanding how best to work with NestJS

Here is a [Stack Overflow post](https://stackoverflow.com/questions/51707348/nestjs-request-and-application-lifecycle) with some specific questions related to this issue.

## Environment

<pre><code>
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
I'd like to add to this, along with showing how the request flows, can we also get a diagram of how request happens between globally and locally scoped providers? Something that shows what happens if you have, say, a globally scoped validation pipe, a globally scoped interceptor, a locally scoped guard, and a locally scoped transformation pipe? Would it look like this?

`local guard -> global interceptor -> global pipe -> local pipe -> controller -> service -> controller -> global interceptor (outbound) -> client`
