### ISSUE TITLE
Injectable

### ISSUE THREAD

**Issue by henrmota** [nestjs/docs.nestjs.com#1760]
[ ] Regression
[ ] Bug report
[ ] Feature request
[x ] Documentation issue or request (new chapter/page)
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.

One thing that I cannot understand, is if ```@Injectable()``` means that a class can be the receptor of a dependency, it's the subject of dependency or both. Does anyone can clarify me and possibly update the documentation to clarify that.

**Comment by jmcdo29** [comment]
[There's a long conversation about a similar topic here](https://github.com/nestjs/nest/issues/6081).

In short, the `@Injectable()` decorators is necessary to let nest do dependency injection on the current class, because of how decorators and typescript work. Without it, the class can still be injected into something else, but classes cannot be injected into it.

**Comment by henrmota** [comment]
Thank you @jmcdo29. My doubt was not of how it works, but what it means, because I am going to give a presentation to my company about NestJs and I want to be clear about this. I think it would be nice to see de documentation updated to clarify this.

**Comment by jmcdo29** [comment]
I'm gonna be trying to work on some of that documentation this weekend and making it clearer

**Comment by ericmorand** [comment]
> Without it, the class can still be injected into something else, but classes cannot be injected into it.

I think the accurate description is that classes cannot be injected into it _implicitely_ - i.e. inferring the token from the type of the argument. Injecting a class or a value using the `@Inject` decorator works, whether the class is `@Injectable` or not.

```ts
class Foo1 {
    constructor(bar: Bar) {
        // bar is undefined
    }
}

class Foo1 {
    constructor(@Inject(Bar) bar: Bar) {
        // bar is set
    }
}
```

**Comment by jmcdo29** [comment]
You're absolutely right about that @ericmorand. It all has to do with how Typescript works with decorators. The was a `@typescript-eslint` issue that came up because eslint saw type imports not being used as `import type...` and it thought it was an error, and with the `--fix` glad "fixed" them, but in doing this it broke how nest functioned because Typescript no longer reflected the type metadata. 

Anyways it opened up a large discussion about how all of that worked and eventually a PR, by there's a ton of great information about decorators and Typescript in that issue and PR. I'll link it when I find it

**Comment by henrmota** [comment]
This is awesome, Dependency Injection in ```node.js```  is very hard without a beast like ```nest.js``` handling it for us.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/1754
