### ISSUE TITLE
Supporting PDF format

### ISSUE THREAD

**Issue by CountZero1981** [nestjs/docs.nestjs.com#183]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request (new chapter/page)
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

No documentation in pdf format; documentation can be read only when connected to the Internet.

## Expected behavior

Would be nice to have this documentation in pdf format.

## What is the motivation / use case for changing the behavior?

I often travel to long distances with a PocketBook. Having a pdf file with NestJS documentation would help me to learn it faster. Reading documentation on a PocketBook which isn't Internet capable helps to evade distractions.

**Comment by dianjuar** [comment]
Maybe a PWA could solve that problem and there is no need to create/maintain something new because you can access to the web page without internet.

The official documentation of [angular.io](https://angular.io/) is a PWA and you can access to the documentation in offline mode.

I just tested and works, but you must have internet the first time you visit the page to "download" it.

Resuming, I think PWA could work but I need more technical knowledge of that topic.
![HoarseGloomyArizonaalligatorlizard-small (1)](https://user-images.githubusercontent.com/7026066/56152830-58aea480-5f7a-11e9-8e5b-113099d013f5.gif)

**Comment by BrunnerLivio** [comment]
Printing pages manually to PDF has been improved a while back ago. I have also created a script which downloads all the pages in PDF format: [BrunnerLiviodocs.nestjs.com-pdf](https://github.com/BrunnerLivio/docs.nestjs.com-pdf)

**Comment by amadeous** [comment]
@dianjuar This would be awesome! Do you know if it would be possible to add this feature to the doc website without too much trouble?
It doesn't seem to be possible right now.

**Comment by dianjuar** [comment]
@amadeous Well is just pass the web application to a progressive web application with its implications. It's better to open a new issue explaining why do you want it and a discussion can be placed there.
