### ISSUE TITLE
All Features Full Documentation

### ISSUE THREAD

**Issue by kosiakMD** [nestjs/docs.nestjs.com#1868]
## Is your feature request related to a problem? Please describe.
As a new user of this framework, I can't find a lot of descriptions, TS interfaces, and documentations common things it does have
The official Docs are really restricted. The search engine either can't search all features or there are not enough feature descriptions.

## Describe the solution you'd like
I'd like to find more documentation and explanations, especially with already integrated services/libraries. As we can find standalone services/libraries documentation but combined are also not full.

#### Documentation

e.g. @Res - response; 
Express 'Response' inheritance ...
methods: ...
e.g. Axios Obreserveble response or handling data receiving

## What is the motivation / use case for changing the behavior?
To give sufficient information, description, explanations with examples for users to popularize this framework

**Comment by kamilmysliwiec** [comment]
Any ideas on how we can make the docs better are more than welcome. However, for this, we need more details & some specifics of what exactly is missing atm. If you can create an issue with a more detailed description of what exactly you'd like to see (in which page/chapter/section), that would be great. Also, PRs are more than welcome so if you're willing to contribute and instead of writing an issue, propose a solution/improvement right away, that would be great too!
