### ISSUE TITLE
Archive older versions of the migration-guide page

### ISSUE THREAD

**Issue by chriszrc** [nestjs/docs.nestjs.com#2037]
## I'm submitting a...

- [ ] Regression 
- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request (new chapter/page)
- [ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.

## Current behavior

The migration-guide page only shows the notes for upgrading from the last previous version, but some of us (me) are just upgrading from 6-7, and those notes are difficult to pick out from the git history. 

## Expected behavior

Ideally, previous versions of the migration-guide page would be archived on the docs site.  And Changelog links like the one here:

https://github.com/nestjs/nest/releases?after=v7.0.7

Would still work, because they'd point to the v6->v7 page.

**Comment by jmcdo29** [comment]
You can still get to the older migration guides. If you choose the version on the docs (at the bottom of the left sidebar) you will be taken to the docs for that version. Then you can choose migration guide and see what the changes are. Due to how the Angular Router and Dgeni are set up, direct links to older versions don't work, but the docs do still exist
<img width="236" alt="Screen Shot 2021-09-07 at 7 46 11 AM" src="https://user-images.githubusercontent.com/28268680/132364877-15af180f-17e0-4b7c-8fb0-9023adc8a66a.png">

**Comment by chriszrc** [comment]
@jmcdo29 Ah, thank you! I didn't actually realize that version button actually did anything, lol-
