### ISSUE TITLE
Docs: code grouping the npm installation commands

### ISSUE THREAD

**Issue by Scrip7** [nestjs/docs.nestjs.com#2200]
## I'm submitting a...
- [x] Feature request

Since nest CLI officially supports choosing different package managers while creating a new project:

![image](https://user-images.githubusercontent.com/37535505/152663423-812b2724-f2a4-4365-a55e-7fd9c1f0e935.png)

I was wondering if it is possible to have package managers (`npm` | `yarn` | `pnpm`) as tabs right above the `npm install` command on every doc page.

So by clicking each tab the installation command would change to their equivalent package manager.

I did a little research about this feature and apparently, it's called "code grouping"
Here is a live example with the VuePress built-in component:
- https://vuepress.vuejs.org/theme/default-theme-config.html#code-groups-and-code-blocks
- https://v2.vuepress.vuejs.org/reference/default-theme/components.html#codegroupitem

**Comment by kamilmysliwiec** [comment]
I don't see a reason why we should be bloating the documentation with different package managers. Installing dependencies is a very straightforward process and it boils down to running a single command that just slightly varies between package managers. If you've decided to use Yarn instead of NPM (which is the default) we assume that you're aware of what's the equivalent of `npm i` in Yarn.
