### ISSUE TITLE
app.useGlobalGuards(new RolesGuard()) does not work as-written

### ISSUE THREAD

**Issue by Offlein** [nestjs/docs.nestjs.com#248]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request (new chapter/page)
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
When implementing a global `RolesGuard` class, as described in this "Guards" documentation page, the class requires a Reflector object to be injected via constructor. There is no explanation for how to do this.

## Expected behavior
It appears that a Reflector instance needs to be created using `app.get(Reflector)`, and then passed in as a parameter of the `new RolesGuard(...)` function call.

## Environment

<pre><code>
For Tooling issues:
- Node version: v8.11.3
- Platform:  Linux, Windows
</code></pre>

**Comment by Offlein** [comment]
Just a further comment after beating my head around this longer:

It would appear that a guard registered as a global guard will be forced to run prior to any controller/route guards.

Unless I'm mistaken, the direct result of this is that, if I want to use RolesGuard as written (that is, one that relies on `request.user`, or a user authenticated from, presumably, Passport's `AuthGuard` class, `RolesGuard` will run prior to `AuthGuard` and this property will not be set, essentially making `RolesGuard` useless when run in global mode?

One caveat: It may also be that I'm interpreting the instructions incorrectly. It says that some module will need to provide the `RolesGuard` module - I was putting that in my base module (which I call, and which is commonly called `AppModule`). I wonder if the ordering could somehow be defined better here?

Either way, I think a reasonable reading of this documentation nets broken results. :(

**Comment by johnbiundo** [comment]
@Offlein Sorry for the slow response.  Do you happen to have a repo that demonstrates this?

**Comment by Offlein** [comment]
@johnbiundo Hi John, thanks for the reply. Not currently; it has been 6 months since I thought about this particular issue. In mid-August I will be taking a look at this project again, but until then I'm afraid I can't be helpful. I will close until then, and I can reopen?

**Comment by johnbiundo** [comment]
👍 Thanks @Offlein

**Comment by greenreign** [comment]
I'm going through the documentation today and this is still very much an issue.  Roles guard cannot be used as described in the documentation.  All examples seem to inject RolesGuard the class directly from a controller.
```
@Controller('cats')
@UseGuards(AuthGuard, RolesGuard)
@Roles('admin')
export class CatsController[]
```

Whereas according to the docs it could (should) be
```
@Controller('cats')
@UseGuards(AuthGuard)
@Roles('admin')
export class CatsController[]
```

```
 app.useGlobalGuards(RolesGuard);  //nope wants CanActivate[]
 app.useGlobalGuards(new RolesGuard(); // nope, constructor requires Reflector
```

**Comment by johnbiundo** [comment]
I think there are a couple of things going on here.

As @Offlein suggested, there is an ordering issue when mixing global (`app.useGlobalGuards`) and controller or method-scoped guards.  The ordering (as he suggests, global first, then controller, then method) causes the issue he describes.  The solution to this is to ensure that guards are executed in the correct order.  For example, in the controller, locate the `@UseGuards(AuthGuard('jwt'), RolesGuard)` at the controller level, applying the Guards in the correct order for all methods in the controller.  You could also run `@UseGuards(AuthGuard('jwt'))` at the controller level, and apply the `RoleGuard` selectively to certain handlers.

I think the docs are a little bit disjointed around this.  The problem is that we document Guards before we document all the other moving parts (the attempt to do so is in the Authentication chapter).  So the Guards chapter clearly suggests (with an actual code example!) using a global `RolesGuard` along with controller JWT guard, and this doesn't work.

My initial thought is to do a little reorganization and put some of the "putting it all together" material from the Guards chapter into the Authentication chapter where we can show the fuller context.  The down side is that chapter is ALREADY very long, and it might be a bit harder to find that material when someone is looking at the Guards chapter as a reference.  Perhaps a small pointer to this section of the Authentication chapter inside the Guards chapter would do it.  Anyway, hopefully this serves as a placeholder until we get some more feedback on the best approach, and hopefully anyone tripping on this issue finds this.
