### ISSUE TITLE
Remove routes order section (controllers)

### ISSUE THREAD

**Issue by kamilmysliwiec** [nestjs/docs.nestjs.com#464]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request (new chapter/page)
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Expected behavior

Ref https://github.com/nestjs/nest/issues/2232

## Environment

<pre><code>
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by johnbiundo** [comment]
@kamilmysliwiec Confirming I see same behavior.  Route order is not dependent on registration order.  Are there other considerations?  In https://docs.nestjs.com/controllers#routes-order we state "all path parameters are optional", but that would also appear not to be true.  If this is true, we can simply remove the **Routes order** section of the page.  

Do you happen to know if this is due to any change in Express?  If so, do we need to note a breaking change in behavior?

**Comment by julianomqs** [comment]
Hello there,

I'm creating a small prototype project with Nest.js, and I stumbled upon the routes order section of the documentation.

Apparently the situation described in the routes section does not occur.

This example:

```javascript
@Get(":id")
async findOne(@Param("id") id: string): Promise<string> {
    return "Obter um segmento pelo id.";
}

@Get()
async findAll(): Promise<string> {
    return "Obter todos os segmentos.";
}
```

Works correctly.

The `async` does not make a difference, it works with or without it.

I'm using the following versions:
- Node version `v12.4.0`
- `@nestjs/common: 6.0.0`.
- `@nestjs/core: 6.0.0`.
- `@nestjs/platform-express: 6.0.0`.
