### ISSUE TITLE
Dark mode for docs.nestjs.com

### ISSUE THREAD

**Issue by SOHELAHMED7** [nestjs/docs.nestjs.com#613]
I request dark mode for docs.nestjs.com

It is not a task/bug/discussion ... but just a enhancement

I would be keen to help you if you need more info about this issue.

**Comment by kamilmysliwiec** [comment]
We don't plan to introduce another colors palette.

**Comment by kruegernet** [comment]
View the [docs on github](https://github.com/nestjs/docs.nestjs.com/tree/master/content) and use a stylus dark theme for github to save your eyes.

**Comment by tukusejssirs** [comment]
> We don't plan to introduce another colors palette.

I wish this decision would be re-evaluated. No need to ad colour palette configuration, just add a dark-light toggle (you can inspire yourself from [this website](https://mikro-orm.io/)).

Actually, three parts of the website only need to change:
- right sidebar (navigation);
- main part (content);
- left sidebar (TOC).

All of them share the same style, therefore it should be a piece of cake to implement this.

**Comment by micalevisk** [comment]
@tukusejssirs what about https://github.com/nestjs/docs.nestjs.com/pull/1138

**Comment by tukusejssirs** [comment]
@micalevisk, yeah, that looks nice. I’ve found that PR  _after_ I commented here. Sorry for the noise. I’ve already liked that PR and I hope it’ll get merged ASAP.

In the meanwhile, I modified a [CSS stylesheet to my needs and likes](https://www.reddit.com/r/Nestjs_framework/comments/iz8hdh/comment/hlnwshk), so that my eyes don’t hurt while learning the awesome Nest framework. :wink:

**Comment by viralRupani** [comment]
Please add dark mode to docs.nestjs.com 😭.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/pull/1138
