### ISSUE TITLE
getType() in ExecutionContext and ArgumentsHost

### ISSUE THREAD

**Issue by kamilmysliwiec** [nestjs/docs.nestjs.com#673]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request (new chapter/page)
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Expected behavior

Ref https://github.com/nestjs/nest/issues/1581

## Environment

<pre><code>
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by hexonaut** [comment]
Sounds good @johnbiundo. My main use case was for a universal role guard: https://github.com/BellwoodStudios/canary/blob/master/src/role/role.guard.ts. The use case is pretty self-explanatory, but happy to elaborate if you need.

**Comment by johnbiundo** [comment]
@hexonaut Thanks for the quick response!  Your code is easy enough to understand.  I'm wondering if anyone has an additional example of guard/interceptor that runs across HTTP and microservices context using this technique?

**Comment by johannesschobel** [comment]
Dear all,

I am currently struggling with the same problem - i want to distinguish if the request is from a regular `http call` (i.e., to my REST api), or if it origins from `GraphQL`. If i call the `context.getType()`, both requests result in `http`, so it is not possible for me to distinguish in an easy way if it is a `http` or `graphql` context.

I ended up with some solution provided by @hexonaut (i.e., i am checking the length of the context arguments). This is, however, not the best solution, i guess.

Would it be possible to add a `graphql` type and handle this internally in Nest? I don't know where / how, but i guess it would be better to handle it framework-internally instead of externally in my application. What do you think @kamilmysliwiec ?

All the best

**Comment by kamilmysliwiec** [comment]
Tracking here https://github.com/nestjs/docs.nestjs.com/pull/954
