### ISSUE TITLE
Microservices (core)

### ISSUE THREAD

**Issue by kamilmysliwiec** [nestjs/docs.nestjs.com#98]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request (new chapter/page)
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Expected behavior

The documentation should be more detailed about how the microservice communication works internally.

## Environment

<pre><code>
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by deveddev** [comment]
Any update on this?  I think clarity around communication between services built with nest would be most helpful.

**Comment by Can-Sahin** [comment]
I wanna re-ask now again. Microservices is a big question mark for me. I really dont understand how its working, whats the fundamentals of its logics, how it can be used to create another type of microservices for instance AWS SQS SNS KINESIS -> Lambda for event-driven architectures. 

Would really appreciate a detail docs on microservices rather than 'you can do it like this and this'. Because it seems super promising for many things.

**Comment by kamilmysliwiec** [comment]
We have just merged a big PR with a bunch of improvements. We also plan to add **Custom strategy** chapter shortly.
